### ISSUE TITLE
Horse 

### ISSUE THREAD

**Issue by 1388zandi** [replicate/scribble-diffusion#81]
```[tasklist]
### Tasks
- [ ] https://github.com/replicate/scribble-diffusion/issues/78
- [ ] https://github.com/replicate/scribble-diffusion/issues/76
- [ ] https://github.com/replicate/scribble-diffusion/pull/75
- [ ] https://github.com/replicate/scribble-diffusion/issues/68
```

**Comment by 1388zandi** [comment]
Horse

**Comment by 1388zandi** [comment]
Horse

**Comment by 1388zandi** [comment]
![Uploading FaceApp_1704963844722.jpg…]()
